
enum Card {
    TWO_HEARTS,
    THREE_HEARTS,
    FOUR_HEARTS,
    FIVE_HEARTS,
    SIX_HEARTS,
    SEVEN_HEARTS,
    EIGHT_HEARTS,
    NINE_HEARTS,
    TEN_HEARTS,
    JAC_HEARTS,
    QUEEN_HEARTS,
    KING_HEARTS,
    ACE_HEARTS,

    TWO_SPADES,
    THREE_SPADES,
    FOUR_SPADES,
    FIVE_SPADES,
    SIX_SPADES,
    SEVEN_SPADES,
    EIGHT_SPADES,
    NINE_SPADES,
    TEN_SPADES,
    JAC_SPADES,
    QUEEN_SPADES,
    KING_SPADES,
    ACE_SPADES,

    TWO_CLUBS,
    THREE_CLUBS,
    FOUR_CLUBS,
    FIVE_CLUBS,
    SIX_CLUBS,
    SEVEN_CLUBS,
    EIGHT_CLUBS,
    NINE_CLUBS,
    TEN_CLUBS,
    JAC_CLUBS,
    QUEEN_CLUBS,
    KING_CLUBS,
    ACE_CLUBS,

    TWO_DIAMONDS,
    THREE_DIAMONDS,
    FOUR_DIAMONDS,
    FIVE_DIAMONDS,
    SIX_DIAMONDS,
    SEVEN_DIAMONDS,
    EIGHT_DIAMONDS,
    NINE_DIAMONDS,
    TEN_DIAMONDS,
    JAC_DIAMONDS,
    QUEEN_DIAMONDS,
    KING_DIAMONDS,
    ACE_DIAMONDS,
}


const CARD_VALUE = {
    Card.TWO_HEARTS: 2,
    Card.THREE_HEARTS: 3,
    Card.FOUR_HEARTS: 4,
    Card.FIVE_HEARTS: 5,
    Card.SIX_HEARTS: 6,
    Card.SEVEN_HEARTS: 7,
    Card.EIGHT_HEARTS: 8,
    Card.NINE_HEARTS: 9,
    Card.TEN_HEARTS: 10,
    Card.JAC_HEARTS: 10,
    Card.QUEEN_HEARTS: 10,
    Card.KING_HEARTS: 10,
    Card.ACE_HEARTS: 1,

    Card.TWO_SPADES: 2,
    Card.THREE_SPADES: 3,
    Card.FOUR_SPADES: 4,
    Card.FIVE_SPADES: 5,
    Card.SIX_SPADES: 6,
    Card.SEVEN_SPADES: 7,
    Card.EIGHT_SPADES: 8,
    Card.NINE_SPADES: 9,
    Card.TEN_SPADES: 10,
    Card.JAC_SPADES: 10,
    Card.QUEEN_SPADES: 10,
    Card.KING_SPADES: 10,
    Card.ACE_SPADES: 1,

    Card.TWO_CLUBS: 2,
    Card.THREE_CLUBS: 3,
    Card.FOUR_CLUBS: 4,
    Card.FIVE_CLUBS: 5,
    Card.SIX_CLUBS: 6,
    Card.SEVEN_CLUBS: 7,
    Card.EIGHT_CLUBS: 8,
    Card.NINE_CLUBS: 9,
    Card.TEN_CLUBS: 10,
    Card.JAC_CLUBS: 10,
    Card.QUEEN_CLUBS: 10,
    Card.KING_CLUBS: 10,
    Card.ACE_CLUBS: 1,

    Card.TWO_DIAMONDS: 2,
    Card.THREE_DIAMONDS: 3,
    Card.FOUR_DIAMONDS: 4,
    Card.FIVE_DIAMONDS: 5,
    Card.SIX_DIAMONDS: 6,
    Card.SEVEN_DIAMONDS: 7,
    Card.EIGHT_DIAMONDS: 8,
    Card.NINE_DIAMONDS: 9,
    Card.TEN_DIAMONDS: 10,
    Card.JAC_DIAMONDS: 10,
    Card.QUEEN_DIAMONDS: 10,
    Card.KING_DIAMONDS: 10,
    Card.ACE_DIAMONDS: 1,
}
